export enum NationEnum {
  RANDOM = "Random",
  ASIA = "Asia",
  EUROPE = "Europe",
  NORTH_AMERICA = "North America",
  SOUTH_AMERICA = "South America",
  GERMANY = "Germany",
  FRANCE = "France",
  ENGLAND = "England",
  USA = "USA",
  ITALIA = "Italia",
  RUSSIA = "Russia",
  INDONESIA = "Indonesia",
  MALAYSIA = "Malaysia",
  PHILIPPINES = "Philippines",
  INDIA = "India",
  AUSTRALIA = "Australia",
}
